# ============================================================
# HireLog — AWS SAM Infrastructure Template
# ============================================================
# This file IS the cloud infrastructure. SAM reads it and
# creates/updates a CloudFormation stack that provisions:
#
#   - 2 DynamoDB tables  (Users, Jobs)
#   - 5 Lambda functions (register, login, create_job, get_jobs, update_job)
#   - 1 Lambda function  (ghost_checker — no API route, EventBridge only)
#   - 1 API Gateway      (HTTP API, auto-created by SAM from the events below)
#   - 1 EventBridge rule (daily cron trigger for ghost_checker)
#   - IAM roles          (auto-created per Lambda by SAM)
#
# DEPLOY:
#   sam build
#   sam deploy --guided   ← first time (creates samconfig.toml)
#   sam deploy            ← every time after
# ============================================================


AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31   # tells CloudFormation this is a SAM template

Description: HireLog — Serverless job application tracker

#=============== Parameter =================#

Parameters:
 JwtSecret:
  Type: String
  NoEcho: true    #never show in console or log 
  Description: secret key uesd to sign and verify 

 AllowedOrigin:
  Type: String
  Default : "*"
  Description: CORS allowed origin

#========= Global =================#
#Anything here is inherited by ALL Lambda functions below.
#saves repeating the same block 6 times.

Globals:
 Function:
  Runtime: python3.12
  Timeout: 10   #seconds
  MemorySize: 128    #MByte
  CodeUri: .
  Layers:
   - !Ref DependenciesLayer # shared pip packages (boto3, PyJWT, bcrypt, etc.)
  
  Environment:
   Variables:
    JWT_SECRET: !Ref JwtSecret
    ALLOWED_ORIGIN : !Ref AllowedOrigin
    AWS_REGION_NAME: !Ref AWS::Region
    USER_TABLE_NAME: !Ref UsersTable
    JOBS_TABLE_NAME: !Ref JobsTable


#======== Resources ============#
  
Resources:
 #---------- lambda layer (shared dependencies)------
 DependenciesLayer:
  Type: AWS::Serverless::LayerVersion
  Properties:
   LayerName: hirelog-dependencies
   Description: PyJWT, bcrypt, boto3, pydantic, python-dotenv
   ContentUri: .
   CompatibleRuntimes:
    - python3.12
   RetentionPolicy: Delete  #old layer clean up auto
  Metadata:
   BuildMethod: python3.12  #tell SAM to pip install req.txt here


 #--------- AUTH lambdas-------------
 RegisterFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-register
   Handler: lambdas/auth/register.handler
   Description: POST /auth/register - create acc and return JWT
   Policies:
    - DynamoDBCrudPolicy:
       TableName: !Ref UsersTable
   Events:
    ApiEvent:
     Type: HttpApi    #create API Gateway http
     Properties:
      Path: /auth/register
      Method: POST
      ApiId: !Ref HireLogApi

 LoginFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-login
   Handler: lambdas/auth/login.handler
   Description: POST /auth/login - verify pass and return JWT
   Policies:
    - DynamoDBReadPolicy:
       TableName: !Ref UsersTable

   Events:
    ApiEvent:
     Type: HttpApi
     Properties:
      Path: /auth/login
      Method: POST
      ApiId: !Ref HireLogApi


 #-------- Jobs Lambdas -----------
 CreateJobFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-create-job
   Handler: lambdas/jobs/create_job.handler
   Description: POST /jobs — create a new job application
   Policies:
    - DynamoDBCrudPolicy:
       TableName: !Ref JobsTable
   Events:
    ApiEvent:
     Type: HttpApi
     Properties:
      Path: /jobs
      Method: POST
      ApiId: !Ref HireLogApi
 
 GetJobsFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-get-jobs
   Handler: lambdas/jobs/get_jobs.handler
   Description: GET /jobs — fetch all job applications for the authed user
   Policies:
    - DynamoDBReadPolicy:
       TableName: !Ref JobsTable
   Events:
    ApiEvent:
     Type: HttpApi
     Properties:
      Path: /jobs
      Method: GET
      ApiId: !Ref HireLogApi

 UpateJobsFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-update-jobs
   Handler: lambdas/jobs/update_job.handler
   Description: PATCH /jobs/{job_id} — partial update on a job application
   Policies:
    - DynamoDBCrudPolicy:
       TableName: !Ref JobsTable
   Events:
    ApiEvent:
     Type: HttpApi
     Properties:
      Path: /jobs/{job_id}
      Method: PATCH
      ApiId: !Ref HireLogApi

 #------ Scheduler Lambda ------------
 GhostCheckeFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: hirelog-ghost-ghost_checker
   Handler: lambdas/scheduler/ghost_checker.handler
   Description: Daily job — marks stale applications as "ghosted"
   Timeout: 60    
   Policies:
    - DynamoDBCrudPolicy:
       TableName: !Ref JobsTable
   Events:
    DailyTrigger:
     Type: ScheduleV2     #EventBridge Scheduler

     Properties:
      ScheduleExpression: "cron(0 9 * * ? *)" # 9:00 am UTC daily 
      Description: Daily ghost job checker 

 #========= API Gateway===================
 HireLogApi:
  Type: AWS::Serverless::HttpApi
  Properties:
   StageName: prod
   CorsConfiguration:
    AllowOrigins:
     - !Ref AllowedOrigin
    AllowHeaders:
     - Content-Type
     - Authorization
    AllowMethods:
     - GET
     - POST
     - PATCH
     - OPTIONS

 #============== DynamoDB ==============
 UsersTable:
  Type: AWS::DynamoDB::Table
  Properties:
   TableName: hirelog-users
   BillingMode: PAY_PER_REQUEST

   AttributeDefinitions:
    - AttributeName: email
      AttributeType: S

   KeySchema:
    - AttributeName: email
      KeyType: HASH

 

 JobsTable:
  Type: AWS::DynamoDB::Table
  Properties:
   TableName: hirelog-jobs
   BillingMode: PAY_PER_REQUEST
   AttributeDefinitions:
    - AttributeName: job_id
      AttributeType: S
    - AttributeName: user_id
      AttributeType: S

   KeySchema:
    - AttributeName: job_id
      KeyType: HASH
   GlobalSecondaryIndexes:
    - IndexName: user_id-index
      KeySchema:
       - AttributeName: user_id
         KeyType: HASH

      Projection:
       ProjectionType: ALL


# ============= Output =================#

Outputs:
 ApiBaseUrl:
  Description: Base URL for HireLog API 
  Value: !Sub "https://${HireLogApi}.execute-api.${AWS::Region}.amazonaws.com/prod"


 UsersTableName:
  Description: DynamoDB User table IndexName
  Value: !Ref UsersTable

 JobsTableName:
  Description: DynamoDB Jobs table name 
  Value: !Ref JobsTable